### ISSUE TITLE
Should make the value of attribute make_cache be equal to enabled

### ISSUE THREAD

**Issue by wenchma** [chef-cookbooks/yum-erlang_solutions#3]
If set ['yum']['erlang_solutions']['enabled'] to false, attribute make_cache is not set, the chef client will run into error when yum makecache, because the default value of make_cache is true, https://github.com/opscode-cookbooks/yum/blob/master/resources/repository.rb#L40

The related code :
https://github.com/opscode-cookbooks/yum-erlang_solutions/blob/master/recipes/default.rb#L25

**Comment by someara** [comment]
I just saw this... triaging as a bug for now, I need to set up this as a test condition

**Comment by someara** [comment]
Fixed up in underlying yum_repository resource 
https://github.com/chef-cookbooks/yum/blob/2f9cb507c0938011d284ccd1c305365351f73130/providers/repository.rb#L49-L51
